# Generated by Django 4.0 on 2021-12-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_read_at_alter_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='name',
        ),
    ]
